### ISSUE TITLE
Enable eslint & obey react-hooks rules

### ISSUE THREAD

**Issue by csantos1113** [AndreasFaust/react-raster#11]
While trying to work on this other issue #10 - I noticed there is no eslint configuration file, and there are a a few react-hooks exceptions we should be addressing.

**Comment by AndreasFaust** [comment]
Added `eslint.rc`.
Does it need specific eslint-modules additionally?

**Comment by AndreasFaust** [comment]
Seems to be fixed. Please reopen, if not.
