### ISSUE TITLE
Console logs in latest version

### ISSUE THREAD

**Issue by BahaMagi** [AndreasFaust/react-raster#17]
Updating to 8.0.1 causes left over debug logs to appear in the console:

![image](https://user-images.githubusercontent.com/52032030/124597007-39560780-de63-11eb-855d-9e589c2f078f.png)

They are in `react-raster/src/Box/index.tsx`

```
44:   console.log(context.breakpoint);
45:   console.log(propsNormalized.breakpoint);
```

and `react-raster/src/Box/utils/useNormalize.ts`

```
25:   console.log(mergedProps);
```

**Comment by AndreasFaust** [comment]
Thanks for reporting. Fixed, please update to `8.0.3`.
