### ISSUE TITLE
Is it possible to have different colspan per breakpoints too?

### ISSUE THREAD

**Issue by csantos1113** [AndreasFaust/react-raster#9]
Hey @AndreasFaust thanks for the library.

I wondering if there is an easy way to configure how many columns I have per breakpoint?

<img width="744" alt="Screen Shot 2021-01-22 at 12 49 43 PM" src="https://user-images.githubusercontent.com/9648559/105526436-68f7c580-5cb0-11eb-8236-e7359626b72c.png">

Thanks

**Comment by AndreasFaust** [comment]
Hello Cesar, 
at the moment this is not possible. But I am right now working on this repo and can add this functionality, because I also think, that it is useful in some cases.

**Comment by AndreasFaust** [comment]
Just relesed verion `6.6.0`, which allows different `colspans` at different `breakpoints`.

**Comment by csantos1113** [comment]
wonderful! that was really fast.
I appreciate your quick help with it ;)

**Comment by AndreasFaust** [comment]
You’re welcome! It was just a minor thing and I really want to push this library. Soon there will be a real documentation website based on Facebook’s Docusaurus. If you like `react-raster` tell your friends and colleagues.
